version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ../data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      mynetwork:
        ipv4_address: 172.16.0.2

  python:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      mynetwork:
        ipv4_address: 172.16.0.3
    command: python aio_bot_start.py

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/24