version: '3'
services:
  bot:
    build: .
    command: python aio_bot_start.py
    restart: always
    depends_on:
      - db
    networks:
      - custom


  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - custom


networks:
  custom:
    driver: bridge
