version: '3'
services:
  mongodb:
    container_name: "MG_BOT_DB"
    image: mongo
    restart: always
    volumes:
      - ../data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - mg_bot_net

  python:
    container_name: "MG_BOT"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - mg_bot_net
    command: python app.py

networks:
   mg_bot_net:
    driver: bridge
